## Numpy Module functions with Examples

In [ ]:
import numpy as np

In [ ]:
a=np.array([[10,20],[30,40]])

In [ ]:
print(a)

[[10 20]
 [30 40]]


In [ ]:
a[1][0]

30

In [ ]:
b=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(b)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [ ]:
b[1][1][0]

70

In [ ]:
x=[10,20,30]
y=np.array(a,dtype=float)
print(y)

[[10. 20.]
 [30. 40.]]


In [ ]:
a=[[10,20],[30,40]]
b=np.asarray(a,order='c')
print(b)

[[10 20]
 [30 40]]


In [ ]:
a=[[10,20],[30,40]]
b=np.asarray(a,order='F')

In [ ]:
for i in np.nditer(b):
  print(i)

10
30
20
40


In [ ]:
a=b"Welcome to Numpy"


In [ ]:
np.frombuffer(a,dtype="S1",count=10)

array([b'W', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o'],
      dtype='|S1')

In [ ]:
a=[10,30,40,50]


In [ ]:
np.fromiter(a,dtype=int,count=3)

array([10, 30, 40])

In [ ]:
a=np.zeros(3)
print(a)


[0. 0. 0.]


In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,3)

array([[0.83833786, 0.44200167, 0.74564067],
       [0.20234138, 0.16606406, 0.47274678]])

In [ ]:
a=np.arange(10,20,1)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
np.arange(0,100,20,dtype=float)

array([ 0., 20., 40., 60., 80.])

In [ ]:
a=np.arange(10,70,10)
print(a)

[10 20 30 40 50 60]


In [ ]:
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(10,100,10,endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [ ]:
np.linspace(10,100,10,endpoint=False,retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

In [ ]:
np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [ ]:
a=np.linspace(10,90,9)
print(a)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [ ]:
b=np.reshape(a,[3,3])
print(b)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [ ]:
np.size(a)

9

In [ ]:
a.dtype

dtype('float64')

In [ ]:
b[0]

array([10., 20., 30.])

In [ ]:
s=np.arange(10,100,10)
print(s)

[10 20 30 40 50 60 70 80 90]


In [ ]:
n=np.copy(a)
c=b.view()
c

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [ ]:
print("a=",a,"b=",b,"c=",c)

a= [10. 20. 30. 40. 50. 60. 70. 80. 90.] b= [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] c= [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [ ]:
# Sorting
m=np.array([[40,30,20],[10,50,5]])
m

array([[40, 30, 20],
       [10, 50,  5]])

In [ ]:
np.sort(m,axis=0)

array([[10, 30,  5],
       [40, 50, 20]])

In [ ]:
np.sort(m,axis=1)

array([[20, 30, 40],
       [ 5, 10, 50]])

In [ ]:
d=np.dtype([('name','S1'),('perc',float)])
d
marks=np.array([("ramu",95.0),("hari",75.4),("raju",98.3)])
marks


array([['ramu', '95.0'],
       ['hari', '75.4'],
       ['raju', '98.3']], dtype='<U32')

In [ ]:
# append()
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
np.append(a,b).reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
a


array([[10, 20],
       [30, 40]])

In [ ]:
np.insert(a,3,[35,45])

array([10, 20, 30, 35, 45, 40])

In [ ]:
# delete
a

array([[10, 20],
       [30, 40]])

In [ ]:
np.delete(a,2)


array([10, 20, 40])

In [ ]:
a

array([[10, 20],
       [30, 40]])

In [ ]:
# concatenate()
np.concatenate((a,b))



array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
res=np.stack((a,b))
res

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [ ]:
np.stack((a,b),axis=1)

array([[[10, 20],
        [50, 60]],

       [[30, 40],
        [70, 80]]])

In [ ]:
a

array([[10, 20],
       [30, 40]])

In [ ]:
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
np.hstack((a,b))

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [ ]:
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

In [ ]:
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
y=np.split(x,2)
y

[array([10, 20, 30, 40, 50, 60]), array([ 70,  80,  90, 100, 110, 120])]

In [ ]:
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.split(x,(2,6))

[array([10, 20]), array([30, 40, 50, 60]), array([ 70,  80,  90, 100])]

In [ ]:
a=np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
np.where(a==80)

(array([2]), array([1]))

In [ ]:
np.where(a%20==0)

(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))

In [ ]:
a=np.array([10,20,30,40,50,60])
np.searchsorted(a,40)

3

In [ ]:
# divide() function
import numpy as np

# input_array
arr1 = [2, 27, 2, 21, 23]
a=np.array(arr1)
arr2 = [2, 3, 4, 5, 6]
b=np.array(arr2)
out = np.divide(a, b)
out

array([1.        , 9.        , 0.5       , 4.2       , 3.83333333])

In [ ]:
mul=np.multiply(a,b)
mul

array([  4,  81,   8, 105, 138])

In [ ]:
ex=np.exp(a)
ex

array([7.38905610e+00, 5.32048241e+11, 7.38905610e+00, 1.31881573e+09,
       9.74480345e+09])

In [ ]:
np.sqrt(a)

array([1.41421356, 5.19615242, 1.41421356, 4.58257569, 4.79583152])

In [ ]:
a=np.array((10,20,30,40,50,60),ndmin=2)
a

array([[10, 20, 30, 40, 50, 60]])

In [ ]:
np.reshape(a,(2,3))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
b=np.array((1,2,3,4,5,6),ndmin=2)
b


array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.reshape(b,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array_equal(a,b)

False

In [ ]:
a=np.array([[10,20],[30,40],[50,60]])
np.min(a)

10

In [ ]:
np.min(a,axis=1)

array([10, 30, 50])

In [ ]:
np.min(a,axis=0)

array([10, 20])

In [ ]:
np.median(a)

35.0